modLoader="javafml"
loaderVersion="[4,)"
license="GNU Lesser General Public License version 2.1 (LGPLv2.1)"

[[mods]]
modId="flois_precambrian"
version="1.4.1"
displayName="floi's Precambrian mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flois-precambrian"
logoFile="logo.png"
credits="made by floi"
authors="Floi"
description="floi's Precambrian mod for 1.21.1 neoforge"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.flois_precambrian]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.flois_precambrian]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration